[project]
name = "etucode-ml-tag-servise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = []
requires-python = ">=3.14"
dependencies = [
    "torch",
    "fastapi",
    "uvicorn",
    "pydantic",
    "transformers",
    "sentence-transformers",
    "scipy",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[project.scripts]
etucode-ml-tag-servise = "etucode_ml_tag_servise:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
